<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?><div id="onestepcheckout-review-comments-simple">
    <div class="field-row">
        <label for="comments"><?php echo $this->__('Comments') ?></label>
        <br />
        <div class="input-box">
            <textarea name="comments" id="comments" rows="2"><?php echo $this->getComments(); ?></textarea>
        </div>
    </div>
</div>